// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: id.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for IdService service

func NewIdServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for IdService service

type IdService interface {
	GetId(ctx context.Context, in *IdRequest, opts ...client.CallOption) (*IdResponse, error)
}

type idService struct {
	c    client.Client
	name string
}

func NewIdService(name string, c client.Client) IdService {
	return &idService{
		c:    c,
		name: name,
	}
}

func (c *idService) GetId(ctx context.Context, in *IdRequest, opts ...client.CallOption) (*IdResponse, error) {
	req := c.c.NewRequest(c.name, "IdService.GetId", in)
	out := new(IdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IdService service

type IdServiceHandler interface {
	GetId(context.Context, *IdRequest, *IdResponse) error
}

func RegisterIdServiceHandler(s server.Server, hdlr IdServiceHandler, opts ...server.HandlerOption) error {
	type idService interface {
		GetId(ctx context.Context, in *IdRequest, out *IdResponse) error
	}
	type IdService struct {
		idService
	}
	h := &idServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&IdService{h}, opts...))
}

type idServiceHandler struct {
	IdServiceHandler
}

func (h *idServiceHandler) GetId(ctx context.Context, in *IdRequest, out *IdResponse) error {
	return h.IdServiceHandler.GetId(ctx, in, out)
}
